config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Myapp::Application.routes.draw do

  resources :requests_closures

  resources :careers

  resources :roles

  get "requests/registrarme" => "requests#registrarme"
  get "requests/quitarme" => "requests#quitarme"
  get "requests/cambioestado" => "requests#cambioestado"
  get "user_in_requests/borrar_todo" => "user_in_requests#borrar_todo"

  resources :user_in_requests

  resources :requests

  resources :courses

  resources :schedules

  resources :states

  get "sessions/new"
  get "users/new"
  get '/users/destroy/:id', to: 'users#destroy'
  get "home/index"
	get "users/usuario"

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "users/usuario" => "users#usuario", :as => "usuario"

constraints(AuthConstraint.new) do
	root :to => 'requests#rooturl', :as => "authenticated_root"
end

root :to => "sessions#new"
resources :users
resources :sessions

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name
  has_many :requests
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
	if current_user
		if current_user.role_id == 2
	    @states = State.all
		else
			redirect_to requests_path
		end
	else
		redirect_to log_in_path
	end
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
	if current_user
		if current_user.role_id == 2
	    @state = State.new
		else
			redirect_to requests_path
		end
	else
		redirect_to log_in_path
	end
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
		if current_user.role_id == 2
		  @state = State.new(state_params)

		  respond_to do |format|
		    if @state.save
		      format.html { redirect_to @state, notice: 'El estado fue creado exitosamente.' }
		      format.json { render action: 'show', status: :created, location: @state }
		    else
		      format.html { render action: 'new' }
		      format.json { render json: @state.errors, status: :unprocessable_entity }
		    end
		  end
		else
			redirect_to requests_path
		end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
		if current_user.role_id == 2
		  respond_to do |format|
		    if @state.update(state_params)
		      format.html { redirect_to @state, notice: 'El estado ha sido actualizado.' }
		      format.json { head :no_content }
		    else
		      format.html { render action: 'edit' }
		      format.json { render json: @state.errors, status: :unprocessable_entity }
		    end
		  end
		else
			redirect_to requests_path
		end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
		if current_user.role_id == 2
		  @state.destroy
		  respond_to do |format|
		    format.html { redirect_to states_url }
		    format.json { head :no_content }
		  end
		else
			redirect_to requests_path
		end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
			if current_user
      @state = State.find(params[:id])
			else
			redirect_to log_in_path
			end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  	 <div class="box-body">
	  	<div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-check-square-o"></i></span>
		   <%= f.text_field :name, class:"form-control",:placeholder => "Ingrese Estado" %>  		  
	 	</div>
	      </div>
	  <div class="box-footer">
	  <p><%= f.submit 'Crear Estado', class: "btn btn-primary"  %></p>
	  </div>
<% end %>


</section>
</div>

app/views/states/edit.html.erb
<% if current_user %>
<div class="content-wrapper">
 <section class="content-header">

<% if userIsAdmin %>
	<div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Editar Estado</h3>
                </div>	


	<%= render 'form' %>

	<%= link_to 'Mostrar', @state %> |
	<%= link_to 'Regresar', states_path %>
<% else %>
	<%= controller.redirect_to requests_path %>
<% end %>

</section>
</div>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>

app/views/states/index.html.erb
<div class="content-wrapper">
 <section class="content-header">
 <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Lista de Estados</h3>
<!-- search                   
		<div class="box-tools">
                    <div class="input-group">
                      <input name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search" type="text">
                      <div class="input-group-btn">
                        <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                      </div>
                    </div>
                  </div>
	-->
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <tbody><tr>
		      <th>Estado</th>
		      <th></th>
		      <th></th>
		      <th></th>
		    </tr>
		    <% @states.each do |state| %>
		      <tr>
			<td><%= state.name %></td>
			<td><%= link_to 'Mostrar', state %></td>
			<td><%= link_to 'Editar', edit_state_path(state) %></td>
			<td><%= link_to 'Borrar', state, method: :delete, data: { confirm: '¿Borrar estado?' } %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		</div><!-- /.box-body -->
              </div><!-- /.box -->
            </div>
          </div>

	<div class="box-footer">
	<%= link_to 'Nuevo estado', new_state_path, class: "btn btn-primary" %>
	</div>

</section>
</div>

app/views/states/new.html.erb
<div class="content-wrapper">
 <section class="content-header">
<div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Nuevo Estado</h3>
                </div>	

<%= render 'form' %>

<%= link_to 'Regresar', states_path %>

app/views/states/show.html.erb
<% if current_user %>
<div class="content-wrapper">
 <section class="content-header">

<% if userIsAdmin %>
	<p id="notice"><%= notice %></p>
	<div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Informacion de Estado</h3>
                </div>

	<div class="box-body">
	<div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-check-square-o"></i></span>
		    <input class="form-control" placeholder="<%= @state.name %>" disabled="" type="text">
	 	</div>
	<br>

	<%= link_to 'Editar', edit_state_path(@state) %> |
	<%= link_to 'Regresar', states_path %>
<% else %>
	<%= controller.redirect_to requests_path %>
<% end %>


</section>
</div>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>