config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Myapp::Application.routes.draw do

  resources :requests_closures

  resources :careers

  resources :roles

  get "requests/registrarme" => "requests#registrarme"
  get "requests/quitarme" => "requests#quitarme"
  get "requests/cambioestado" => "requests#cambioestado"
  get "user_in_requests/borrar_todo" => "user_in_requests#borrar_todo"

  resources :user_in_requests

  resources :requests

  resources :courses

  resources :schedules

  resources :states

  get "sessions/new"
  get "users/new"
  get '/users/destroy/:id', to: 'users#destroy'
  get "home/index"
	get "users/usuario"

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "users/usuario" => "users#usuario", :as => "usuario"

constraints(AuthConstraint.new) do
	root :to => 'requests#rooturl', :as => "authenticated_root"
end

root :to => "sessions#new"
resources :users
resources :sessions

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :name
  has_many :requests
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
		if current_user
		if current_user.role_id == 2
	    @schedules = Schedule.all
		else
			redirect_to requests_path
		end
		else
		redirect_to log_in_path
		end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
		if current_user
		if current_user.role_id == 2
    	@schedule = Schedule.new
		else
			redirect_to requests_path
		end
		else
		redirect_to log_in_path
		end
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
		if current_user.role_id == 2
		  @schedule = Schedule.new(schedule_params)

		  respond_to do |format|
		    if @schedule.save
		      format.html { redirect_to @schedule, notice: 'El horario fue creado exitosamente.' }
		      format.json { render action: 'show', status: :created, location: @schedule }
		    else
		      format.html { render action: 'new' }
		      format.json { render json: @schedule.errors, status: :unprocessable_entity }
		    end
		  end
		else
			redirect_to requests_path
		end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
		if current_user.role_id == 2
		  respond_to do |format|
		    if @schedule.update(schedule_params)
		      format.html { redirect_to @schedule, notice: 'El horario ha sido actualizado.' }
		      format.json { head :no_content }
		    else
		      format.html { render action: 'edit' }
		      format.json { render json: @schedule.errors, status: :unprocessable_entity }
		    end
		  end
		else 
			redirect_to requests_path
		end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
		if current_user.role_id == 2
		  @schedule.destroy
		  respond_to do |format|
		    format.html { redirect_to schedules_url }
		    format.json { head :no_content }
		  end
		else
			redirect_to requests_path
		end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
			if current_user
      @schedule = Schedule.find(params[:id])
			else
			redirect_to log_in_path
			end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:name)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
		
	
  	 <div class="box-body">
	  	<div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
		   <%= f.text_field :name, class:"form-control",:placeholder => "Ingrese Horario" %>  		  
	 	</div>
	      </div>

  	<div class="box-footer">
	  <p><%= f.submit 'Crear Horario', class: "btn btn-primary"  %></p>
	  </div>
<% end %>

</section>
</div>

app/views/schedules/edit.html.erb
<% if current_user %>
<div class="content-wrapper">
 <section class="content-header">

<% if userIsAdmin %>
	<div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Editando Horarios</h3>
                </div>

	<%= render 'form' %>

	<%= link_to 'Mostrar', @schedule %> |
	<%= link_to 'Regresar', schedules_path %>
<% else %>
	<%= controller.redirect_to requests_path %>
<% end %>

</section>
</div>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>

app/views/schedules/index.html.erb
<div class="content-wrapper">
 <section class="content-header">
<div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Listado de Horarios Disponibles</h3>
<!-- search                   
		<div class="box-tools">
                    <div class="input-group">
                      <input name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search" type="text">
                      <div class="input-group-btn">
                        <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                      </div>
                    </div>
                  </div>
	-->
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <tbody><tr>
		      <th>Horario</th>
		      <th></th>
		      <th></th>
		      <th></th>
		    </tr>
		    <% @schedules.each do |schedule| %>
		      <tr>
			<td><%= schedule.name %></td>
			<td><%= link_to 'Mostrar', schedule %></td>
			<td><%= link_to 'Editar', edit_schedule_path(schedule) %></td>
			<td><%= link_to 'Borrar', schedule, method: :delete, data: { confirm: '¿Borrar horario?' } %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		</div><!-- /.box-body -->
              </div><!-- /.box -->
            </div>
          </div>

<div class="box-footer">
<%= link_to 'Nuevo horario', new_schedule_path, class: "btn btn-primary" %>
</div>
</section>
</div>

app/views/schedules/new.html.erb
<div class="content-wrapper">
 <section class="content-header">

<div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Nuevo Horario</h3>
                </div>

<%= render 'form' %>

<%= link_to 'Regresar', schedules_path %>

</section>
</div>

app/views/schedules/show.html.erb
<% if current_user %>
<div class="content-wrapper">
 <section class="content-header">

<% if userIsAdmin %>
	<p id="notice"><%= notice %></p>
	<div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Informacion de Horario</h3>
                </div>

	<div class="box-body">
	<div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
		    <input class="form-control" placeholder="<%= @schedule.name %>" disabled="" type="text">
	 	</div>
	<br>

	<%= link_to 'Editar', edit_schedule_path(@schedule) %> |
	<%= link_to 'Regresar', schedules_path %>
<% else %>
	<%= controller.redirect_to requests_path %>
<% end %>
</section>
</div>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>