config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Myapp::Application.routes.draw do

  resources :requests_closures

  resources :careers

  resources :roles

  get "requests/registrarme" => "requests#registrarme"
  get "requests/quitarme" => "requests#quitarme"
  get "requests/cambioestado" => "requests#cambioestado"
  get "user_in_requests/borrar_todo" => "user_in_requests#borrar_todo"

  resources :user_in_requests

  resources :requests

  resources :courses

  resources :schedules

  resources :states

  get "sessions/new"
  get "users/new"
  get '/users/destroy/:id', to: 'users#destroy'
  get "home/index"
	get "users/usuario"

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "users/usuario" => "users#usuario", :as => "usuario"

constraints(AuthConstraint.new) do
	root :to => 'requests#rooturl', :as => "authenticated_root"
end

root :to => "sessions#new"
resources :users
resources :sessions

end

app/models/role.rb
class Role < ActiveRecord::Base
attr_accessible :name
has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
		if current_user
		if current_user.role_id == 2
    @roles = Role.all
		else
			redirect_to requests_path
		end
		else
		redirect_to log_in_path
		end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
		if current_user
		if current_user.role_id == 2
    @role = Role.new
		else
			redirect_to requests_path
		end
		else
		redirect_to log_in_path
		end
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
		if current_user.role_id == 2
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'El rol fue creado.' }
        format.json { render action: 'show', status: :created, location: @role }
      else
        format.html { render action: 'new' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
		else
			redirect_to requests_path
		end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
		if current_user.role_id == 2
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'El rol fue actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
		else
			redirect_to requests_path
		end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
		if current_user.role_id == 2
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
		else
			redirect_to requests_path
		end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
			if current_user
      @role = Role.find(params[:id])
		else
			redirect_to log_in_path
		end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  	 <div class="box-body">
	  	<div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-sitemap"></i></span>
		   <%= f.text_field :name, class:"form-control",:placeholder => "Ingrese Rol" %>  		  
	 	</div>
	      </div>

  	<div class="box-footer">
	  <p><%= f.submit 'Crear Rol', class: "btn btn-primary"  %></p>
	  </div>
<% end %>

app/views/roles/edit.html.erb
<div class="content-wrapper">
 <section class="content-header">
 <% if current_user %>
<% if userIsAdmin %>

  <div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Editando Rol</h3>
                </div>	


<%= render 'form' %>

<%= link_to 'Mostrar', @role %> |
<%= link_to 'Regresar', roles_path %>
<% else %>
	<%= controller.redirect_to requests_path %>
<% end %>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>
</section>
</div>

app/views/roles/index.html.erb
<div class="content-wrapper">
 <section class="content-header">
 
	<div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Listado de Roles</h3>
<!-- search                   
		<div class="box-tools">
                    <div class="input-group">
                      <input name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search" type="text">
                      <div class="input-group-btn">
                        <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                      </div>
                    </div>
                  </div>
	-->
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <tbody><tr>
		      <th>Rol</th>
		      <th></th>
		      <th></th>
		      <th></th>
		    </tr>
		    <% @roles.each do |role| %>
		      <tr>
			<td><%= role.name %></td>
			<td><%= link_to 'Mostrar', role %></td>
			<td><%= link_to 'Editar', edit_role_path(role) %></td>
			<td><%= link_to 'Borrar', role, method: :delete, data: { confirm: 'Borrar rol?' } %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		</div><!-- /.box-body -->
              </div><!-- /.box -->
            </div>
          </div>

	<div class="box-footer">
	<%= link_to 'Nuevo Rol', new_role_path, class: "btn btn-primary" %>
	</div>

</section>
</div>

app/views/roles/new.html.erb
<div class="content-wrapper">
 <section class="content-header">


  <div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Nuevo Rol</h3>
                </div>	

<%= render 'form' %>

</section>
</div>

app/views/roles/show.html.erb
<% if current_user %>
<div class="content-wrapper">
 <section class="content-header">

<% if userIsAdmin %>
<p id="notice"><%= notice %></p>
	<div class="row">
            <!-- left column -->
            <div class="col-md-6">	
		<div class="box box-info">
                <div class="box-header">
                  <h3 class="title-box">Informacion del Rol</h3>
                </div>

	<div class="box-body">
	<div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-sitemap"></i></span>
		    <input class="form-control" placeholder="<%= @role.name %>" disabled="" type="text">
	 	</div>
	<br>


<%= link_to 'Editar', edit_role_path(@role) %> |
<%= link_to 'Regresar', roles_path %>
<% else %>
	<%= controller.redirect_to requests_path %>
<% end %>

</section>
</div>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>