config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Myapp::Application.routes.draw do

  resources :requests_closures

  resources :careers

  resources :roles

  get "requests/registrarme" => "requests#registrarme"
  get "requests/quitarme" => "requests#quitarme"
  get "requests/cambioestado" => "requests#cambioestado"
  get "user_in_requests/borrar_todo" => "user_in_requests#borrar_todo"

  resources :user_in_requests

  resources :requests

  resources :courses

  resources :schedules

  resources :states

  get "sessions/new"
  get "users/new"
  get '/users/destroy/:id', to: 'users#destroy'
  get "home/index"
	get "users/usuario"

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "users/usuario" => "users#usuario", :as => "usuario"

constraints(AuthConstraint.new) do
	root :to => 'requests#rooturl', :as => "authenticated_root"
end

root :to => "sessions#new"
resources :users
resources :sessions

end

app/models/user_in_request.rb
class UserInRequest < ActiveRecord::Base
  attr_accessible :user_id, :request_id
  belongs_to :user
  belongs_to :request
end

app/controllers/user_in_requests_controller.rb
class UserInRequestsController < ApplicationController
  before_action :set_user_in_request, only: [:show, :edit, :update, :destroy]

  # GET /user_in_requests
  # GET /user_in_requests.json
  def index
	if current_user
		if current_user.role_id == 2
    	@user_in_requests = UserInRequest.all
		else
			redirect_to requests_path
		end
	else
		redirect_to log_in_path
	end
  end

  # GET /user_in_requests/1
  # GET /user_in_requests/1.json
  def show
  end

  # GET /user_in_requests/new
  def new
		if current_user
		if current_user.role_id == 2
	    @user_in_request = UserInRequest.new
		else
			redirect_to requests_path
		end
		else
		redirect_to log_in_path
		end
  end

  # GET /user_in_requests/1/edit
  def edit
  end

  # POST /user_in_requests
  # POST /user_in_requests.json
  def create
		if current_user.role_id == 2
		  @user_in_request = UserInRequest.new(user_in_request_params)

		  respond_to do |format|
		    if @user_in_request.save
		      format.html { redirect_to @user_in_request, notice: 'La propuesta del usuario fue creada exitosamente.' }
		      format.json { render action: 'show', status: :created, location: @user_in_request }
		    else
		      format.html { render action: 'new' }
		      format.json { render json: @user_in_request.errors, status: :unprocessable_entity }
		    end
		  end
		else
			redirect_to requests_path
		end
  end

  # PATCH/PUT /user_in_requests/1
  # PATCH/PUT /user_in_requests/1.json
  def update
		if current_user.role_id == 2
		  respond_to do |format|
		    if @user_in_request.update(user_in_request_params)
		      format.html { redirect_to @user_in_request, notice: 'La propuesta del usuario ha sido actualizada.' }
		      format.json { head :no_content }
		    else
		      format.html { render action: 'edit' }
		      format.json { render json: @user_in_request.errors, status: :unprocessable_entity }
		    end
		  end
		else
			redirect_to requests_path
		end
  end

  # DELETE /user_in_requests/1
  # DELETE /user_in_requests/1.json
  def destroy
		if current_user.role_id == 1 || current_user.role_id == 2
		  @user_in_request.destroy
		  respond_to do |format|
		    format.html { redirect_to user_in_requests_url }
		    format.json { head :no_content }
		  end
		else
			redirect_to requests_path
		end
  end

  def borrar_todo
    if userIsCoordinator
      Request.all.each do |request|
        if request.course.career == current_user.career
          UserInRequest.where(request_id: request.id).each do |uir|
            uir.destroy
          end
          request.destroy
        end
      end
    end
    
    if userIsAdmin
      @temp = params[:career_id].to_i
      Request.all.each do |request|
        if request.course.career.id == @temp
          UserInRequest.where(request_id: request.id).each do |uir|
            uir.destroy
          end
          request.destroy
        end
      end

      if @temp == 0
        Request.destroy_all
        UserInRequest.destroy_all
        ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'requests'")
        ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'user_in_requests'")
      end
    end
    redirect_to "/requests"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_in_request
			if current_user
      @user_in_request = UserInRequest.find(params[:id])
			else
			redirect_to log_in_path
			end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_in_request_params
      params.require(:user_in_request).permit(:user_id, :request_id)
    end
end

app/helpers/user_in_requests_helper.rb
module UserInRequestsHelper
end

app/views/user_in_requests/_form.html.erb
<%= form_for(@user_in_request) do |f| %>
  <% if @user_in_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_in_request.errors.count, "error") %> prohibited this user_in_request from being saved:</h2>

      <ul>
      <% @user_in_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Usuario %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :Propuesta %><br>
    <%= f.number_field :request_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


</section>
</div>

app/views/user_in_requests/edit.html.erb
<div class="content-wrapper">
 <section class="content-header">
 <% if current_user %>
<% if userIsAdmin %>
	<h1>Editando la propuesta del usuario</h1>

	<%= render 'form' %>

	<%= link_to 'Mostrar', @user_in_request %> |
	<%= link_to 'Regresar', user_in_requests_path %>
<% else %>
	<%= controller.redirect_to requests_path %>
<% end %>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>
</section>
</div>

app/views/user_in_requests/index.html.erb
<div class="content-wrapper">
 <section class="content-header">

<h1>Listado de los usuarios en las propuestas</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Propuesta</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_in_requests.each do |user_in_request| %>
      <tr>
        <td><%= user_in_request.user_id %></td>
        <td><%= user_in_request.request_id %></td>
        <td><%= link_to 'Mostrar', user_in_request %></td>
        <td><%= link_to 'Editar', edit_user_in_request_path(user_in_request) %></td>
        <td><%= link_to 'Borrar', user_in_request, method: :delete, data: { confirm: '¿Borrar usuario de la propuesta?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva propuesta de usuario', new_user_in_request_path %>

</section>
</div>

app/views/user_in_requests/new.html.erb
<div class="content-wrapper">
 <section class="content-header">

<h1>Nuevo usuario en la propuesta</h1>

<%= render 'form' %>

<%= link_to 'Regresar', user_in_requests_path %>

app/views/user_in_requests/show.html.erb
<div class="content-wrapper">
 <section class="content-header">
 <% if current_user %>
<% if userIsAdmin %>
	<p id="notice"><%= notice %></p>

	<p>
		<strong>Usuario:</strong>
		<%= @user_in_request.user_id %>
	</p>

	<p>
		<strong>Propuesta:</strong>
		<%= @user_in_request.request_id %>
	</p>

	<%= link_to 'Editar', edit_user_in_request_path(@user_in_request) %> |
	<%= link_to 'Regresar', user_in_requests_path %>
<% else %>
	<%= controller.redirect_to requests_path %>
<% end %>
<% else %>
<%= controller.redirect_to log_in_path %>
<% end %>
</section>
</div>